### PR TITLE
Add load function for measures and value sets

### PR DESCRIPTION
**Pull request by mattrbianchi**

### CODE REVIEW

**Review by okeefm — COMMENTED** [review]
Does this need to be updated now that `cdatools` has been updated? E.g. re-run `make`?

**Comment by mattrbianchi** [comment]
Yes, but only because I rebased. Let me handle that really quick.

**Comment by mattrbianchi** [comment]
Alright, the mac `.so` is updated. But the linux one will still be out of date (this is how it has been). We should probably investigate if we can cross-compile a `.so` file like we can a normal go project. There might be some obstacles with the `.so` file though.

**Review by okeefm — APPROVED** [review]
If we're comfortable with `libgocda-linux.so` being out-of-date (as it has been), I'm okay with merging this.

**Comment by mattrbianchi** [comment]
I am, we can change this later in a different PR. It's not like I'm taking away functionality, this is just how it has been.

**Review by dczulada — COMMENTED** [review]
+1

**Pull request merged**
